# Generated by Django 4.1.7 on 2023-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.AddField(
            model_name='client',
            name='date',
            field=models.DateField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.CharField(default='This is my message', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
