# Generated by Django 4.1.7 on 2023-03-22 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoSystem', '0002_remove_client_country_client_date_client_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='date',
            field=models.DateTimeField(default=0),
        ),
    ]
